export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  ROLE_PANACIM_VIEW = 'ROLE_PANACIM_VIEW',
  ROLE_PANACIM_UPDATE = 'ROLE_PANACIM_UPDATE',
  ROLE_PANACIM_APPROVE = 'ROLE_PANACIM_APPROVE',
  ROLE_PANACIM_ADMIN = 'ROLE_PANACIM_ADMIN',
  USER = '',
}
