package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttributesTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributesTypeAllPropertiesEquals(
        AttributesType expected,
        AttributesType actual
    ) {
        assertAttributesTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertAttributesTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributesTypeAllUpdatablePropertiesEquals(
        AttributesType expected,
        AttributesType actual
    ) {
        assertAttributesTypeUpdatableFieldsEquals(expected, actual);
        assertAttributesTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributesTypeAutoGeneratedPropertiesEquals(
        AttributesType expected,
        AttributesType actual
    ) {
        assertThat(actual)
            .as("Verify AttributesType auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributesTypeUpdatableFieldsEquals(
        AttributesType expected,
        AttributesType actual
    ) {
        assertThat(actual)
            .as("Verify AttributesType relevant properties")
            .satisfies(a ->
                assertThat(a.getDescription())
                    .as("check description")
                    .isEqualTo(expected.getDescription())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributesTypeUpdatableRelationshipsEquals(
        AttributesType expected,
        AttributesType actual
    ) {
        // empty method
    }
}
