package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryNotificationAllPropertiesEquals(
        DeliveryNotification expected,
        DeliveryNotification actual
    ) {
        assertDeliveryNotificationAutoGeneratedPropertiesEquals(
            expected,
            actual
        );
        assertDeliveryNotificationAllUpdatablePropertiesEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryNotificationAllUpdatablePropertiesEquals(
        DeliveryNotification expected,
        DeliveryNotification actual
    ) {
        assertDeliveryNotificationUpdatableFieldsEquals(expected, actual);
        assertDeliveryNotificationUpdatableRelationshipsEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryNotificationAutoGeneratedPropertiesEquals(
        DeliveryNotification expected,
        DeliveryNotification actual
    ) {
        assertThat(actual)
            .as("Verify DeliveryNotification auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryNotificationUpdatableFieldsEquals(
        DeliveryNotification expected,
        DeliveryNotification actual
    ) {
        assertThat(actual)
            .as("Verify DeliveryNotification relevant properties")
            .satisfies(a ->
                assertThat(a.getDeliveryNotificationCode())
                    .as("check deliveryNotificationCode")
                    .isEqualTo(expected.getDeliveryNotificationCode())
            )
            .satisfies(a ->
                assertThat(a.getInvoiceNumber())
                    .as("check invoiceNumber")
                    .isEqualTo(expected.getInvoiceNumber())
            )
            .satisfies(a ->
                assertThat(a.getContractCode())
                    .as("check contractCode")
                    .isEqualTo(expected.getContractCode())
            )
            .satisfies(a ->
                assertThat(a.getVendorName())
                    .as("check vendorName")
                    .isEqualTo(expected.getVendorName())
            )
            .satisfies(a ->
                assertThat(a.getContNo())
                    .as("check contNo")
                    .isEqualTo(expected.getContNo())
            )
            .satisfies(a ->
                assertThat(a.getEntryDate())
                    .as("check entryDate")
                    .isEqualTo(expected.getEntryDate())
            )
            .satisfies(a ->
                assertThat(a.getNumberOfPo())
                    .as("check numberOfPo")
                    .isEqualTo(expected.getNumberOfPo())
            )
            .satisfies(a ->
                assertThat(a.getNumberOfItem())
                    .as("check numberOfItem")
                    .isEqualTo(expected.getNumberOfItem())
            )
            .satisfies(a ->
                assertThat(a.getStatus())
                    .as("check status")
                    .isEqualTo(expected.getStatus())
            )
            .satisfies(a ->
                assertThat(a.getSource())
                    .as("check source")
                    .isEqualTo(expected.getSource())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getDeletedAt())
                    .as("check deletedAt")
                    .isEqualTo(expected.getDeletedAt())
            )
            .satisfies(a ->
                assertThat(a.getDeletedBy())
                    .as("check deletedBy")
                    .isEqualTo(expected.getDeletedBy())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryNotificationUpdatableRelationshipsEquals(
        DeliveryNotification expected,
        DeliveryNotification actual
    ) {
        // empty method
    }
}
