package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GenTemConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenTemConfigAllPropertiesEquals(
        GenTemConfig expected,
        GenTemConfig actual
    ) {
        assertGenTemConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertGenTemConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenTemConfigAllUpdatablePropertiesEquals(
        GenTemConfig expected,
        GenTemConfig actual
    ) {
        assertGenTemConfigUpdatableFieldsEquals(expected, actual);
        assertGenTemConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenTemConfigAutoGeneratedPropertiesEquals(
        GenTemConfig expected,
        GenTemConfig actual
    ) {
        assertThat(actual)
            .as("Verify GenTemConfig auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenTemConfigUpdatableFieldsEquals(
        GenTemConfig expected,
        GenTemConfig actual
    ) {
        assertThat(actual)
            .as("Verify GenTemConfig relevant properties")
            .satisfies(a ->
                assertThat(a.getTpNk())
                    .as("check tpNk")
                    .isEqualTo(expected.getTpNk())
            )
            .satisfies(a ->
                assertThat(a.getRank())
                    .as("check rank")
                    .isEqualTo(expected.getRank())
            )
            .satisfies(a ->
                assertThat(a.getMfg())
                    .as("check mfg")
                    .isEqualTo(expected.getMfg())
            )
            .satisfies(a ->
                assertThat(a.getQuantityPerBox())
                    .as("check quantityPerBox")
                    .isEqualTo(expected.getQuantityPerBox())
            )
            .satisfies(a ->
                assertThat(a.getNote())
                    .as("check note")
                    .isEqualTo(expected.getNote())
            )
            .satisfies(a ->
                assertThat(a.getNumBoxPerPallet())
                    .as("check numBoxPerPallet")
                    .isEqualTo(expected.getNumBoxPerPallet())
            )
            .satisfies(a ->
                assertThat(a.getBranch())
                    .as("check branch")
                    .isEqualTo(expected.getBranch())
            )
            .satisfies(a ->
                assertThat(a.getGroupName())
                    .as("check groupName")
                    .isEqualTo(expected.getGroupName())
            )
            .satisfies(a ->
                assertThat(a.getCustomerName())
                    .as("check customerName")
                    .isEqualTo(expected.getCustomerName())
            )
            .satisfies(a ->
                assertThat(a.getPoNumber())
                    .as("check poNumber")
                    .isEqualTo(expected.getPoNumber())
            )
            .satisfies(a ->
                assertThat(a.getDateCode())
                    .as("check dateCode")
                    .isEqualTo(expected.getDateCode())
            )
            .satisfies(a ->
                assertThat(a.getItemNoSku())
                    .as("check itemNoSku")
                    .isEqualTo(expected.getItemNoSku())
            )
            .satisfies(a ->
                assertThat(a.getQdsxNo())
                    .as("check qdsxNo")
                    .isEqualTo(expected.getQdsxNo())
            )
            .satisfies(a ->
                assertThat(a.getProductionDate())
                    .as("check productionDate")
                    .isEqualTo(expected.getProductionDate())
            )
            .satisfies(a ->
                assertThat(a.getInspectorName())
                    .as("check inspectorName")
                    .isEqualTo(expected.getInspectorName())
            )
            .satisfies(a ->
                assertThat(a.getInspectionResult())
                    .as("check inspectionResult")
                    .isEqualTo(expected.getInspectionResult())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .isEqualTo(expected.getUpdatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedBy())
                    .as("check updatedBy")
                    .isEqualTo(expected.getUpdatedBy())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenTemConfigUpdatableRelationshipsEquals(
        GenTemConfig expected,
        GenTemConfig actual
    ) {
        assertThat(actual)
            .as("Verify GenTemConfig relationships")
            .satisfies(a ->
                assertThat(a.getMaLenhSanXuat())
                    .as("check maLenhSanXuat")
                    .isEqualTo(expected.getMaLenhSanXuat())
            );
    }
}
