package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ImportVendorTemTransactionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportVendorTemTransactionsAllPropertiesEquals(
        ImportVendorTemTransactions expected,
        ImportVendorTemTransactions actual
    ) {
        assertImportVendorTemTransactionsAutoGeneratedPropertiesEquals(
            expected,
            actual
        );
        assertImportVendorTemTransactionsAllUpdatablePropertiesEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportVendorTemTransactionsAllUpdatablePropertiesEquals(
        ImportVendorTemTransactions expected,
        ImportVendorTemTransactions actual
    ) {
        assertImportVendorTemTransactionsUpdatableFieldsEquals(
            expected,
            actual
        );
        assertImportVendorTemTransactionsUpdatableRelationshipsEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportVendorTemTransactionsAutoGeneratedPropertiesEquals(
        ImportVendorTemTransactions expected,
        ImportVendorTemTransactions actual
    ) {
        assertThat(actual)
            .as("Verify ImportVendorTemTransactions auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportVendorTemTransactionsUpdatableFieldsEquals(
        ImportVendorTemTransactions expected,
        ImportVendorTemTransactions actual
    ) {
        assertThat(actual)
            .as("Verify ImportVendorTemTransactions relevant properties")
            .satisfies(a ->
                assertThat(a.getPoNumber())
                    .as("check poNumber")
                    .isEqualTo(expected.getPoNumber())
            )
            .satisfies(a ->
                assertThat(a.getVendorCode())
                    .as("check vendorCode")
                    .isEqualTo(expected.getVendorCode())
            )
            .satisfies(a ->
                assertThat(a.getVendorName())
                    .as("check vendorName")
                    .isEqualTo(expected.getVendorName())
            )
            .satisfies(a ->
                assertThat(a.getEntryDate())
                    .as("check entryDate")
                    .isEqualTo(expected.getEntryDate())
            )
            .satisfies(a ->
                assertThat(a.getStorageUnit())
                    .as("check storageUnit")
                    .isEqualTo(expected.getStorageUnit())
            )
            .satisfies(a ->
                assertThat(a.getImportTemProfile())
                    .as("check importTemProfile")
                    .isEqualTo(expected.getImportTemProfile())
            )
            .satisfies(a ->
                assertThat(a.getStatus())
                    .as("check status")
                    .isEqualTo(expected.getStatus())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedBy())
                    .as("check updatedBy")
                    .isEqualTo(expected.getUpdatedBy())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            )
            .satisfies(a ->
                assertThat(a.getDeletedBy())
                    .as("check deletedBy")
                    .isEqualTo(expected.getDeletedBy())
            )
            .satisfies(a ->
                assertThat(a.getDeletedAt())
                    .as("check deletedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDeletedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportVendorTemTransactionsUpdatableRelationshipsEquals(
        ImportVendorTemTransactions expected,
        ImportVendorTemTransactions actual
    ) {
        // empty method
    }
}
