package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class InboundWMSBoxAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSBoxAllPropertiesEquals(
        InboundWMSBox expected,
        InboundWMSBox actual
    ) {
        assertInboundWMSBoxAutoGeneratedPropertiesEquals(expected, actual);
        assertInboundWMSBoxAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSBoxAllUpdatablePropertiesEquals(
        InboundWMSBox expected,
        InboundWMSBox actual
    ) {
        assertInboundWMSBoxUpdatableFieldsEquals(expected, actual);
        assertInboundWMSBoxUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSBoxAutoGeneratedPropertiesEquals(
        InboundWMSBox expected,
        InboundWMSBox actual
    ) {
        assertThat(actual)
            .as("Verify InboundWMSBox auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSBoxUpdatableFieldsEquals(
        InboundWMSBox expected,
        InboundWMSBox actual
    ) {
        assertThat(actual)
            .as("Verify InboundWMSBox relevant properties")
            .satisfies(a ->
                assertThat(a.getWarehouseNoteInfoId())
                    .as("check warehouseNoteInfoId")
                    .isEqualTo(expected.getWarehouseNoteInfoId())
            )
            .satisfies(a ->
                assertThat(a.getSerialBox())
                    .as("check serialBox")
                    .isEqualTo(expected.getSerialBox())
            )
            .satisfies(a ->
                assertThat(a.getWmsSendStatus())
                    .as("check wmsSendStatus")
                    .isEqualTo(expected.getWmsSendStatus())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSBoxUpdatableRelationshipsEquals(
        InboundWMSBox expected,
        InboundWMSBox actual
    ) {
        // empty method
    }
}
