package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class InboundWMSPalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSPalletAllPropertiesEquals(
        InboundWMSPallet expected,
        InboundWMSPallet actual
    ) {
        assertInboundWMSPalletAutoGeneratedPropertiesEquals(expected, actual);
        assertInboundWMSPalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSPalletAllUpdatablePropertiesEquals(
        InboundWMSPallet expected,
        InboundWMSPallet actual
    ) {
        assertInboundWMSPalletUpdatableFieldsEquals(expected, actual);
        assertInboundWMSPalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSPalletAutoGeneratedPropertiesEquals(
        InboundWMSPallet expected,
        InboundWMSPallet actual
    ) {
        assertThat(actual)
            .as("Verify InboundWMSPallet auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSPalletUpdatableFieldsEquals(
        InboundWMSPallet expected,
        InboundWMSPallet actual
    ) {
        assertThat(actual)
            .as("Verify InboundWMSPallet relevant properties")
            .satisfies(a ->
                assertThat(a.getInboundWMSSessionId())
                    .as("check inboundWMSSessionId")
                    .isEqualTo(expected.getInboundWMSSessionId())
            )
            .satisfies(a ->
                assertThat(a.getWarehouseNoteInfoId())
                    .as("check warehouseNoteInfoId")
                    .isEqualTo(expected.getWarehouseNoteInfoId())
            )
            .satisfies(a ->
                assertThat(a.getSerialPallet())
                    .as("check serialPallet")
                    .isEqualTo(expected.getSerialPallet())
            )
            .satisfies(a ->
                assertThat(a.getWmsSendStatus())
                    .as("check wmsSendStatus")
                    .isEqualTo(expected.getWmsSendStatus())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSPalletUpdatableRelationshipsEquals(
        InboundWMSPallet expected,
        InboundWMSPallet actual
    ) {
        assertThat(actual)
            .as("Verify InboundWMSPallet relationships")
            .satisfies(a ->
                assertThat(a.getInboundWMSSession())
                    .as("check inboundWMSSession")
                    .isEqualTo(expected.getInboundWMSSession())
            );
    }
}
