package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class InboundWMSSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSSessionAllPropertiesEquals(
        InboundWMSSession expected,
        InboundWMSSession actual
    ) {
        assertInboundWMSSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertInboundWMSSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSSessionAllUpdatablePropertiesEquals(
        InboundWMSSession expected,
        InboundWMSSession actual
    ) {
        assertInboundWMSSessionUpdatableFieldsEquals(expected, actual);
        assertInboundWMSSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSSessionAutoGeneratedPropertiesEquals(
        InboundWMSSession expected,
        InboundWMSSession actual
    ) {
        assertThat(actual)
            .as("Verify InboundWMSSession auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSSessionUpdatableFieldsEquals(
        InboundWMSSession expected,
        InboundWMSSession actual
    ) {
        assertThat(actual)
            .as("Verify InboundWMSSession relevant properties")
            .satisfies(a ->
                assertThat(a.getStatus())
                    .as("check status")
                    .isEqualTo(expected.getStatus())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInboundWMSSessionUpdatableRelationshipsEquals(
        InboundWMSSession expected,
        InboundWMSSession actual
    ) {
        // empty method
    }
}
