package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PalletMngtAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletMngtAllPropertiesEquals(
    PalletMngt expected,
    PalletMngt actual
  ) {
    assertPalletMngtAutoGeneratedPropertiesEquals(expected, actual);
    assertPalletMngtAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletMngtAllUpdatablePropertiesEquals(
    PalletMngt expected,
    PalletMngt actual
  ) {
    assertPalletMngtUpdatableFieldsEquals(expected, actual);
    assertPalletMngtUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletMngtAutoGeneratedPropertiesEquals(
    PalletMngt expected,
    PalletMngt actual
  ) {
    assertThat(actual)
      .as("Verify PalletMngt auto generated properties")
      .satisfies(a ->
        assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
      );
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletMngtUpdatableFieldsEquals(
    PalletMngt expected,
    PalletMngt actual
  ) {
    assertThat(actual)
      .as("Verify PalletMngt relevant properties")
      .satisfies(a ->
        assertThat(a.getSerialPallet())
          .as("check serialPallet")
          .isEqualTo(expected.getSerialPallet())
      )
      .satisfies(a ->
        assertThat(a.getLocationName())
          .as("check locationName")
          .isEqualTo(expected.getLocationName())
      )
      .satisfies(a ->
        assertThat(a.getNumberOfBox())
          .as("check numberOfBox")
          .isEqualTo(expected.getNumberOfBox())
      )
      .satisfies(a ->
        assertThat(a.getTotalQuantity())
          .as("check totalQuantity")
          .isEqualTo(expected.getTotalQuantity())
      )
      .satisfies(a ->
        assertThat(a.getStatus())
          .as("check status")
          .isEqualTo(expected.getStatus())
      )
      .satisfies(a ->
        assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote())
      )
      .satisfies(a ->
        assertThat(a.getCreateAt())
          .as("check createAt")
          .isEqualTo(expected.getCreateAt())
      )
      .satisfies(a ->
        assertThat(a.getCreateBy())
          .as("check createBy")
          .isEqualTo(expected.getCreateBy())
      )
      .satisfies(a ->
        assertThat(a.getUpdatedAt())
          .as("check updatedAt")
          .isEqualTo(expected.getUpdatedAt())
      )
      .satisfies(a ->
        assertThat(a.getUpdatedBy())
          .as("check updatedBy")
          .isEqualTo(expected.getUpdatedBy())
      );
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletMngtUpdatableRelationshipsEquals(
    PalletMngt expected,
    PalletMngt actual
  ) {
    // empty method
  }
}
