package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PalletBoxMappingAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletBoxMappingAllPropertiesEquals(
    PalletBoxMapping expected,
    PalletBoxMapping actual
  ) {
    assertPalletBoxMappingAutoGeneratedPropertiesEquals(expected, actual);
    assertPalletBoxMappingAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletBoxMappingAllUpdatablePropertiesEquals(
    PalletBoxMapping expected,
    PalletBoxMapping actual
  ) {
    assertPalletBoxMappingUpdatableFieldsEquals(expected, actual);
    assertPalletBoxMappingUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletBoxMappingAutoGeneratedPropertiesEquals(
    PalletBoxMapping expected,
    PalletBoxMapping actual
  ) {
    assertThat(actual)
      .as("Verify PalletBoxMapping auto generated properties")
      .satisfies(a ->
        assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
      );
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletBoxMappingUpdatableFieldsEquals(
    PalletBoxMapping expected,
    PalletBoxMapping actual
  ) {
    assertThat(actual)
      .as("Verify PalletBoxMapping relevant properties")
      .satisfies(a ->
        assertThat(a.getSerialPallet())
          .as("check serialPallet")
          .isEqualTo(expected.getSerialPallet())
      )
      .satisfies(a ->
        assertThat(a.getReelIdBox())
          .as("check reelIdBox")
          .isEqualTo(expected.getReelIdBox())
      )
      .satisfies(a ->
        assertThat(a.getCreateAt())
          .as("check createAt")
          .isEqualTo(expected.getCreateAt())
      )
      .satisfies(a ->
        assertThat(a.getCreateBy())
          .as("check createBy")
          .isEqualTo(expected.getCreateBy())
      );
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPalletBoxMappingUpdatableRelationshipsEquals(
    PalletBoxMapping expected,
    PalletBoxMapping actual
  ) {
     assertThat(actual)
       .as("Verify PalletBoxMapping relationships")
       .satisfies(a ->
         assertThat(a.getPalletMngt())
           .as("check palletMngt")
           .isEqualTo(expected.getPalletMngt())
       )
       .satisfies(a ->
         assertThat(a.getVendorLabelInfo())
           .as("check vendorLabelInfo")
           .isEqualTo(expected.getVendorLabelInfo())
       );
   }
}
