package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PoDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoDetailAllPropertiesEquals(
        PoDetail expected,
        PoDetail actual
    ) {
        assertPoDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertPoDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoDetailAllUpdatablePropertiesEquals(
        PoDetail expected,
        PoDetail actual
    ) {
        assertPoDetailUpdatableFieldsEquals(expected, actual);
        assertPoDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoDetailAutoGeneratedPropertiesEquals(
        PoDetail expected,
        PoDetail actual
    ) {
        assertThat(actual)
            .as("Verify PoDetail auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoDetailUpdatableFieldsEquals(
        PoDetail expected,
        PoDetail actual
    ) {
        assertThat(actual)
            .as("Verify PoDetail relevant properties")
            .satisfies(a ->
                assertThat(a.getSapCode())
                    .as("check sapCode")
                    .isEqualTo(expected.getSapCode())
            )
            .satisfies(a ->
                assertThat(a.getSapName())
                    .as("check sapName")
                    .isEqualTo(expected.getSapName())
            )
            .satisfies(a ->
                assertThat(a.getQuantityContainer())
                    .as("check quantityContainer")
                    .isEqualTo(expected.getQuantityContainer())
            )
            .satisfies(a ->
                assertThat(a.getTotalQuantity())
                    .as("check totalQuantity")
                    .isEqualTo(expected.getTotalQuantity())
            )
            .satisfies(a ->
                assertThat(a.getPartNumber())
                    .as("check partNumber")
                    .isEqualTo(expected.getPartNumber())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoDetailUpdatableRelationshipsEquals(
        PoDetail expected,
        PoDetail actual
    ) {
        assertThat(actual)
            .as("Verify PoDetail relationships")
            .satisfies(a ->
                assertThat(a.getImportVendorTemTransactions())
                    .as("check importVendorTemTransactions")
                    .isEqualTo(expected.getImportVendorTemTransactions())
            );
    }
}
