package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PoImportTemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoImportTemAllPropertiesEquals(
        PoImportTem expected,
        PoImportTem actual
    ) {
        assertPoImportTemAutoGeneratedPropertiesEquals(expected, actual);
        assertPoImportTemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoImportTemAllUpdatablePropertiesEquals(
        PoImportTem expected,
        PoImportTem actual
    ) {
        assertPoImportTemUpdatableFieldsEquals(expected, actual);
        assertPoImportTemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoImportTemAutoGeneratedPropertiesEquals(
        PoImportTem expected,
        PoImportTem actual
    ) {
        assertThat(actual)
            .as("Verify PoImportTem auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoImportTemUpdatableFieldsEquals(
        PoImportTem expected,
        PoImportTem actual
    ) {
        assertThat(actual)
            .as("Verify PoImportTem relevant properties")
            .satisfies(a ->
                assertThat(a.getPoNumber())
                    .as("check poNumber")
                    .isEqualTo(expected.getPoNumber())
            )
            .satisfies(a ->
                assertThat(a.getVendorCode())
                    .as("check vendorCode")
                    .isEqualTo(expected.getVendorCode())
            )
            .satisfies(a ->
                assertThat(a.getVendorName())
                    .as("check vendorName")
                    .isEqualTo(expected.getVendorName())
            )
            .satisfies(a ->
                assertThat(a.getEntryDate())
                    .as("check entryDate")
                    .isEqualTo(expected.getEntryDate())
            )
            .satisfies(a ->
                assertThat(a.getStorageUnit())
                    .as("check storageUnit")
                    .isEqualTo(expected.getStorageUnit())
            )
            .satisfies(a ->
                assertThat(a.getQuantityContainer())
                    .as("check quantityContainer")
                    .isEqualTo(expected.getQuantityContainer())
            )
            .satisfies(a ->
                assertThat(a.getTotalQuantity())
                    .as("check totalQuantity")
                    .isEqualTo(expected.getTotalQuantity())
            )
            .satisfies(a ->
                assertThat(a.getStatus())
                    .as("check status")
                    .isEqualTo(expected.getStatus())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedBy())
                    .as("check updatedBy")
                    .isEqualTo(expected.getUpdatedBy())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            )
            .satisfies(a ->
                assertThat(a.getDeletedBy())
                    .as("check deletedBy")
                    .isEqualTo(expected.getDeletedBy())
            )
            .satisfies(a ->
                assertThat(a.getDeletedAt())
                    .as("check deletedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDeletedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoImportTemUpdatableRelationshipsEquals(
        PoImportTem expected,
        PoImportTem actual
    ) {
        // empty method
    }
}
