package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class RdMaterialAttributesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertRdMaterialAttributesAllPropertiesEquals(
        RdMaterialAttributes expected,
        RdMaterialAttributes actual
    ) {
        assertRdMaterialAttributesAutoGeneratedPropertiesEquals(
            expected,
            actual
        );
        assertRdMaterialAttributesAllUpdatablePropertiesEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships)
     * set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertRdMaterialAttributesAllUpdatablePropertiesEquals(
        RdMaterialAttributes expected,
        RdMaterialAttributes actual
    ) {
        assertRdMaterialAttributesUpdatableFieldsEquals(expected, actual);
        assertRdMaterialAttributesUpdatableRelationshipsEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all the auto generated properties
     * (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertRdMaterialAttributesAutoGeneratedPropertiesEquals(
        RdMaterialAttributes expected,
        RdMaterialAttributes actual
    ) {
        assertThat(actual)
            .as("Verify RdMaterialAttributes auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertRdMaterialAttributesUpdatableFieldsEquals(
        RdMaterialAttributes expected,
        RdMaterialAttributes actual
    ) {
        assertThat(actual)
            .as("Verify RdMaterialAttributes relevant properties")
            .satisfies(a ->
                assertThat(a.getAttributes())
                    .as("check attributes")
                    .isEqualTo(expected.getAttributes())
            )
            .satisfies(a ->
                assertThat(a.getDescription())
                    .as("check description")
                    .isEqualTo(expected.getDescription())
            )
            .satisfies(a ->
                assertThat(a.getAttributesType())
                    .as("check attributesType")
                    .isEqualTo(expected.getAttributesType())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedBy())
                    .as("check updatedBy")
                    .isEqualTo(expected.getUpdatedBy())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertRdMaterialAttributesUpdatableRelationshipsEquals(
        RdMaterialAttributes expected,
        RdMaterialAttributes actual
    ) {
        assertThat(actual)
            .as("Verify RdMaterialAttributes relationships")
            .satisfies(a ->
                assertThat(a.getAttributesType())
                    .as("check attributesType")
                    .isEqualTo(expected.getAttributesType())
            );
    }
}
