package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

import com.mycompany.myapp.domain.partner4.SapOitm;

public class SapOitmAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOitmAllPropertiesEquals(
        SapOitm expected,
        SapOitm actual
    ) {
        assertSapOitmAutoGeneratedPropertiesEquals(expected, actual);
        assertSapOitmAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOitmAllUpdatablePropertiesEquals(
        SapOitm expected,
        SapOitm actual
    ) {
        assertSapOitmUpdatableFieldsEquals(expected, actual);
        assertSapOitmUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOitmAutoGeneratedPropertiesEquals(
        SapOitm expected,
        SapOitm actual
    ) {
        assertThat(actual)
            .as("Verify SapOitm auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOitmUpdatableFieldsEquals(
        SapOitm expected,
        SapOitm actual
    ) {
        assertThat(actual)
            .as("Verify SapOitm relevant properties")
            .satisfies(a ->
                assertThat(a.getItemCode())
                    .as("check itemCode")
                    .isEqualTo(expected.getItemCode())
            )
            .satisfies(a ->
                assertThat(a.getItemName())
                    .as("check itemName")
                    .isEqualTo(expected.getItemName())
            )
            .satisfies(a ->
                assertThat(a.getItmsGrpCod())
                    .as("check itmsGrpCod")
                    .isEqualTo(expected.getItmsGrpCod())
            )
            .satisfies(a ->
                assertThat(a.getuPartNumber())
                    .as("check uPartNumber")
                    .isEqualTo(expected.getuPartNumber())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOitmUpdatableRelationshipsEquals(
        SapOitm expected,
        SapOitm actual
    ) {
        // empty method
    }
}
