package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SapOcrdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOcrdAllPropertiesEquals(
        SapOcrd expected,
        SapOcrd actual
    ) {
        assertSapOcrdAutoGeneratedPropertiesEquals(expected, actual);
        assertSapOcrdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOcrdAllUpdatablePropertiesEquals(
        SapOcrd expected,
        SapOcrd actual
    ) {
        assertSapOcrdUpdatableFieldsEquals(expected, actual);
        assertSapOcrdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOcrdAutoGeneratedPropertiesEquals(
        SapOcrd expected,
        SapOcrd actual
    ) {
        assertThat(actual)
            .as("Verify SapOcrd auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOcrdUpdatableFieldsEquals(
        SapOcrd expected,
        SapOcrd actual
    ) {
        assertThat(actual)
            .as("Verify SapOcrd relevant properties")
            .satisfies(a ->
                assertThat(a.getCardCode())
                    .as("check cardCode")
                    .isEqualTo(expected.getCardCode())
            )
            .satisfies(a ->
                assertThat(a.getCardType())
                    .as("check cardType")
                    .isEqualTo(expected.getCardType())
            )
            .satisfies(a ->
                assertThat(a.getCardName())
                    .as("check cardName")
                    .isEqualTo(expected.getCardName())
            )
            .satisfies(a ->
                assertThat(a.getCardFName())
                    .as("check cardFName")
                    .isEqualTo(expected.getCardFName())
            )
            .satisfies(a ->
                assertThat(a.getGroupCode())
                    .as("check groupCode")
                    .isEqualTo(expected.getGroupCode())
            )
            .satisfies(a ->
                assertThat(a.getCurrency())
                    .as("check currency")
                    .isEqualTo(expected.getCurrency())
            )
            .satisfies(a ->
                assertThat(a.getLicTradNum())
                    .as("check licTradNum")
                    .isEqualTo(expected.getLicTradNum())
            )
            .satisfies(a ->
                assertThat(a.getDddId())
                    .as("check dddId")
                    .isEqualTo(expected.getDddId())
            )
            .satisfies(a ->
                assertThat(a.geteMail())
                    .as("check eMail")
                    .isEqualTo(expected.geteMail())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapOcrdUpdatableRelationshipsEquals(
        SapOcrd expected,
        SapOcrd actual
    ) {
        // empty method
    }
}
