package com.mycompany.myapp.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class SapPoInfoTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(
        random.nextInt() + (2 * Integer.MAX_VALUE)
    );
    private static final AtomicInteger intCount = new AtomicInteger(
        random.nextInt() + (2 * Short.MAX_VALUE)
    );

    public static SapPoInfo getSapPoInfoSample1() {
        return new SapPoInfo()
            .id(1L)
            .oporBranch("oporBranch1")
            .oporCanceled("oporCanceled1")
            .oporCardCode("oporCardCode1")
            .oporCardName("oporCardName1")
            .oporComments("oporComments1")
            .oporDepartment("oporDepartment1")
            .oporDocEntry("oporDocEntry1")
            .oporDocNum("oporDocNum1")
            .oporDocStatus("oporDocStatus1")
            .oporInvntSttus("oporInvntSttus1")
            .oporJrnlMemo("oporJrnlMemo1")
            .oporUCoAdd("oporUCoAdd1")
            .oporUCodeInv("oporUCodeInv1")
            .oporUCodeSerial("oporUCodeSerial1")
            .oporUContractDate("oporUContractDate1")
            .oporUDeclarePd("oporUDeclarePd1")
            .oporUDocNum("oporUDocNum1")
            .oporUInvCode("oporUInvCode1")
            .oporUInvCode2("oporUInvCode21")
            .oporUInvSerial("oporUInvSerial1")
            .oporUPurNVGiao("oporUPurNVGiao1")
            .oporUserSign("oporUserSign1")
            .oporCntctCode(1)
            .oporNumAtCard("oporNumAtCard1")
            .oporSlpCode(1)
            .oporOwnerCode(1)
            .oporUHt("oporUHt1")
            .oporUPayment("oporUPayment1")
            .por1BaseDocNum("por1BaseDocNum1")
            .por1BaseEntry("por1BaseEntry1")
            .por1BaseLine("por1BaseLine1")
            .por1BaseRef("por1BaseRef1")
            .por1Currency("por1Currency1")
            .por1DiscPrcnt("por1DiscPrcnt1")
            .poDocEntry("poDocEntry1")
            .por1Dscription("por1Dscription1")
            .por1ItemCode("por1ItemCode1")
            .por1LineNum("por1LineNum1")
            .por1LineStatus("por1LineStatus1")
            .por1LineVendor("por1LineVendor1")
            .por1OpenSumSys("por1OpenSumSys1")
            .por1Price("por1Price1")
            .por1Quantity("por1Quantity1")
            .por1TotalFrgn("por1TotalFrgn1")
            .por1TotalSumsy("por1TotalSumsy1")
            .por1TrgetEntry("por1TrgetEntry1")
            .por1UMcode("por1UMcode1")
            .por1USo("por1USo1")
            .por1UTenkythuat("por1UTenkythuat1")
            .por1UnitMsr("por1UnitMsr1")
            .por1UOMCode("por1UOMCode1")
            .por1VatGroup("por1VatGroup1")
            .por1WhsCode("por1WhsCode1")
            .prMapPo("prMapPo1");
    }

    public static SapPoInfo getSapPoInfoSample2() {
        return new SapPoInfo()
            .id(2L)
            .oporBranch("oporBranch2")
            .oporCanceled("oporCanceled2")
            .oporCardCode("oporCardCode2")
            .oporCardName("oporCardName2")
            .oporComments("oporComments2")
            .oporDepartment("oporDepartment2")
            .oporDocEntry("oporDocEntry2")
            .oporDocNum("oporDocNum2")
            .oporDocStatus("oporDocStatus2")
            .oporInvntSttus("oporInvntSttus2")
            .oporJrnlMemo("oporJrnlMemo2")
            .oporUCoAdd("oporUCoAdd2")
            .oporUCodeInv("oporUCodeInv2")
            .oporUCodeSerial("oporUCodeSerial2")
            .oporUContractDate("oporUContractDate2")
            .oporUDeclarePd("oporUDeclarePd2")
            .oporUDocNum("oporUDocNum2")
            .oporUInvCode("oporUInvCode2")
            .oporUInvCode2("oporUInvCode22")
            .oporUInvSerial("oporUInvSerial2")
            .oporUPurNVGiao("oporUPurNVGiao2")
            .oporUserSign("oporUserSign2")
            .oporCntctCode(2)
            .oporNumAtCard("oporNumAtCard2")
            .oporSlpCode(2)
            .oporOwnerCode(2)
            .oporUHt("oporUHt2")
            .oporUPayment("oporUPayment2")
            .por1BaseDocNum("por1BaseDocNum2")
            .por1BaseEntry("por1BaseEntry2")
            .por1BaseLine("por1BaseLine2")
            .por1BaseRef("por1BaseRef2")
            .por1Currency("por1Currency2")
            .por1DiscPrcnt("por1DiscPrcnt2")
            .poDocEntry("poDocEntry2")
            .por1Dscription("por1Dscription2")
            .por1ItemCode("por1ItemCode2")
            .por1LineNum("por1LineNum2")
            .por1LineStatus("por1LineStatus2")
            .por1LineVendor("por1LineVendor2")
            .por1OpenSumSys("por1OpenSumSys2")
            .por1Price("por1Price2")
            .por1Quantity("por1Quantity2")
            .por1TotalFrgn("por1TotalFrgn2")
            .por1TotalSumsy("por1TotalSumsy2")
            .por1TrgetEntry("por1TrgetEntry2")
            .por1UMcode("por1UMcode2")
            .por1USo("por1USo2")
            .por1UTenkythuat("por1UTenkythuat2")
            .por1UnitMsr("por1UnitMsr2")
            .por1UOMCode("por1UOMCode2")
            .por1VatGroup("por1VatGroup2")
            .por1WhsCode("por1WhsCode2")
            .prMapPo("prMapPo2");
    }

    public static SapPoInfo getSapPoInfoRandomSampleGenerator() {
        return new SapPoInfo()
            .id(longCount.incrementAndGet())
            .oporBranch(UUID.randomUUID().toString())
            .oporCanceled(UUID.randomUUID().toString())
            .oporCardCode(UUID.randomUUID().toString())
            .oporCardName(UUID.randomUUID().toString())
            .oporComments(UUID.randomUUID().toString())
            .oporDepartment(UUID.randomUUID().toString())
            .oporDocEntry(UUID.randomUUID().toString())
            .oporDocNum(UUID.randomUUID().toString())
            .oporDocStatus(UUID.randomUUID().toString())
            .oporInvntSttus(UUID.randomUUID().toString())
            .oporJrnlMemo(UUID.randomUUID().toString())
            .oporUCoAdd(UUID.randomUUID().toString())
            .oporUCodeInv(UUID.randomUUID().toString())
            .oporUCodeSerial(UUID.randomUUID().toString())
            .oporUContractDate(UUID.randomUUID().toString())
            .oporUDeclarePd(UUID.randomUUID().toString())
            .oporUDocNum(UUID.randomUUID().toString())
            .oporUInvCode(UUID.randomUUID().toString())
            .oporUInvCode2(UUID.randomUUID().toString())
            .oporUInvSerial(UUID.randomUUID().toString())
            .oporUPurNVGiao(UUID.randomUUID().toString())
            .oporUserSign(UUID.randomUUID().toString())
            .oporCntctCode(intCount.incrementAndGet())
            .oporNumAtCard(UUID.randomUUID().toString())
            .oporSlpCode(intCount.incrementAndGet())
            .oporOwnerCode(intCount.incrementAndGet())
            .oporUHt(UUID.randomUUID().toString())
            .oporUPayment(UUID.randomUUID().toString())
            .por1BaseDocNum(UUID.randomUUID().toString())
            .por1BaseEntry(UUID.randomUUID().toString())
            .por1BaseLine(UUID.randomUUID().toString())
            .por1BaseRef(UUID.randomUUID().toString())
            .por1Currency(UUID.randomUUID().toString())
            .por1DiscPrcnt(UUID.randomUUID().toString())
            .poDocEntry(UUID.randomUUID().toString())
            .por1Dscription(UUID.randomUUID().toString())
            .por1ItemCode(UUID.randomUUID().toString())
            .por1LineNum(UUID.randomUUID().toString())
            .por1LineStatus(UUID.randomUUID().toString())
            .por1LineVendor(UUID.randomUUID().toString())
            .por1OpenSumSys(UUID.randomUUID().toString())
            .por1Price(UUID.randomUUID().toString())
            .por1Quantity(UUID.randomUUID().toString())
            .por1TotalFrgn(UUID.randomUUID().toString())
            .por1TotalSumsy(UUID.randomUUID().toString())
            .por1TrgetEntry(UUID.randomUUID().toString())
            .por1UMcode(UUID.randomUUID().toString())
            .por1USo(UUID.randomUUID().toString())
            .por1UTenkythuat(UUID.randomUUID().toString())
            .por1UnitMsr(UUID.randomUUID().toString())
            .por1UOMCode(UUID.randomUUID().toString())
            .por1VatGroup(UUID.randomUUID().toString())
            .por1WhsCode(UUID.randomUUID().toString())
            .prMapPo(UUID.randomUUID().toString());
    }
}
