package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SapPor1R1Asserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertSapPor1R1AllPropertiesEquals(
    SapPor1R1 expected,
    SapPor1R1 actual
  ) {
    assertSapPor1R1AutoGeneratedPropertiesEquals(expected, actual);
    assertSapPor1R1AllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertSapPor1R1AllUpdatablePropertiesEquals(
    SapPor1R1 expected,
    SapPor1R1 actual
  ) {
    assertSapPor1R1UpdatableFieldsEquals(expected, actual);
    assertSapPor1R1UpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertSapPor1R1AutoGeneratedPropertiesEquals(
    SapPor1R1 expected,
    SapPor1R1 actual
  ) {
    assertThat(actual)
      .as("Verify SapPor1R1 auto generated properties")
      .satisfies(a ->
        assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
      );
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertSapPor1R1UpdatableFieldsEquals(
    SapPor1R1 expected,
    SapPor1R1 actual
  ) {
    assertThat(actual)
      .as("Verify SapPor1R1 relevant properties")
      .satisfies(a ->
        assertThat(a.getLineNum())
          .as("check lineNum")
          .isEqualTo(expected.getLineNum())
      )
      .satisfies(a ->
        assertThat(a.getBaseRef())
          .as("check baseRef")
          .isEqualTo(expected.getBaseRef())
      )
      .satisfies(a ->
        assertThat(a.getBaseEntry())
          .as("check baseEntry")
          .isEqualTo(expected.getBaseEntry())
      )
      .satisfies(a ->
        assertThat(a.getBaseLine())
          .as("check baseLine")
          .isEqualTo(expected.getBaseLine())
      )
      .satisfies(a ->
        assertThat(a.getLineStatus())
          .as("check lineStatus")
          .isEqualTo(expected.getLineStatus())
      )
      .satisfies(a ->
        assertThat(a.getItemCode())
          .as("check itemCode")
          .isEqualTo(expected.getItemCode())
      )
      .satisfies(a ->
        assertThat(a.getDscription())
          .as("check dscription")
          .isEqualTo(expected.getDscription())
      )
      .satisfies(a ->
        assertThat(a.getQuantity())
          .as("check quantity")
          .usingComparator(bigDecimalCompareTo)
          .isEqualTo(expected.getQuantity())
      )
      .satisfies(a ->
        assertThat(a.getShipDate())
          .as("check shipDate")
          .isEqualTo(expected.getShipDate())
      )
      .satisfies(a ->
        assertThat(a.getPrice())
          .as("check price")
          .isEqualTo(expected.getPrice())
      )
      .satisfies(a ->
        assertThat(a.getCurrency())
          .as("check currency")
          .isEqualTo(expected.getCurrency())
      )
      .satisfies(a ->
        assertThat(a.getDiscPrcnt())
          .as("check discPrcnt")
          .isEqualTo(expected.getDiscPrcnt())
      )
      .satisfies(a ->
        assertThat(a.getTotalSumSy())
          .as("check totalSumSy")
          .isEqualTo(expected.getTotalSumSy())
      )
      .satisfies(a ->
        assertThat(a.getOpenSumSys())
          .as("check openSumSys")
          .isEqualTo(expected.getOpenSumSys())
      )
      .satisfies(a ->
        assertThat(a.getInvntSttus())
          .as("check invntSttus")
          .isEqualTo(expected.getInvntSttus())
      )
      .satisfies(a ->
        assertThat(a.getBaseDocNum())
          .as("check baseDocNum")
          .isEqualTo(expected.getBaseDocNum())
      )
      .satisfies(a ->
        assertThat(a.getuTenkythuat())
          .as("check uTenkythuat")
          .isEqualTo(expected.getuTenkythuat())
      )
      .satisfies(a ->
        assertThat(a.getuSo()).as("check uSo").isEqualTo(expected.getuSo())
      )
      .satisfies(a ->
        assertThat(a.getuMCode())
          .as("check uMCode")
          .isEqualTo(expected.getuMCode())
      )
      .satisfies(a ->
        assertThat(a.getDocEntry())
          .as("check docEntry")
          .isEqualTo(expected.getDocEntry())
      )
      .satisfies(a ->
        assertThat(a.getTotalFrgn())
          .as("check totalFrgn")
          .isEqualTo(expected.getTotalFrgn())
      )
      .satisfies(a ->
        assertThat(a.getVatGroup())
          .as("check vatGroup")
          .isEqualTo(expected.getVatGroup())
      )
      .satisfies(a ->
        assertThat(a.getUomCode())
          .as("check uomCode")
          .isEqualTo(expected.getUomCode())
      )
      .satisfies(a ->
        assertThat(a.getUnitMsr())
          .as("check unitMsr")
          .isEqualTo(expected.getUnitMsr())
      )
      .satisfies(a ->
        assertThat(a.getLineVendor())
          .as("check lineVendor")
          .isEqualTo(expected.getLineVendor())
      )
      .satisfies(a ->
        assertThat(a.getTrgetEntry())
          .as("check trgetEntry")
          .isEqualTo(expected.getTrgetEntry())
      )
      .satisfies(a ->
        assertThat(a.getLineTotal())
          .as("check lineTotal")
          .usingComparator(bigDecimalCompareTo)
          .isEqualTo(expected.getLineTotal())
      )
      .satisfies(a ->
        assertThat(a.getVatPrcnt())
          .as("check vatPrcnt")
          .usingComparator(bigDecimalCompareTo)
          .isEqualTo(expected.getVatPrcnt())
      )
      .satisfies(a ->
        assertThat(a.getPriceAfVat())
          .as("check priceAfVat")
          .usingComparator(bigDecimalCompareTo)
          .isEqualTo(expected.getPriceAfVat())
      )
      .satisfies(a ->
        assertThat(a.getWhsCode())
          .as("check whsCode")
          .isEqualTo(expected.getWhsCode())
      );
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertSapPor1R1UpdatableRelationshipsEquals(
    SapPor1R1 expected,
    SapPor1R1 actual
  ) {
    assertThat(actual)
      .as("Verify SapPor1R1 relationships")
      .satisfies(a ->
        assertThat(a.getDeliveryNotification())
          .as("check deliveryNotification")
          .isEqualTo(expected.getDeliveryNotification())
      );
  }
}
