package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SapPoInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapPoInfoAllPropertiesEquals(
        SapPoInfo expected,
        SapPoInfo actual
    ) {
        assertSapPoInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertSapPoInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapPoInfoAllUpdatablePropertiesEquals(
        SapPoInfo expected,
        SapPoInfo actual
    ) {
        assertSapPoInfoUpdatableFieldsEquals(expected, actual);
        assertSapPoInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapPoInfoAutoGeneratedPropertiesEquals(
        SapPoInfo expected,
        SapPoInfo actual
    ) {
        assertThat(actual)
            .as("Verify SapPoInfo auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapPoInfoUpdatableFieldsEquals(
        SapPoInfo expected,
        SapPoInfo actual
    ) {
        assertThat(actual)
            .as("Verify SapPoInfo relevant properties")
            .satisfies(a ->
                assertThat(a.getOporBranch())
                    .as("check oporBranch")
                    .isEqualTo(expected.getOporBranch())
            )
            .satisfies(a ->
                assertThat(a.getOporCanceled())
                    .as("check oporCanceled")
                    .isEqualTo(expected.getOporCanceled())
            )
            .satisfies(a ->
                assertThat(a.getOporCardCode())
                    .as("check oporCardCode")
                    .isEqualTo(expected.getOporCardCode())
            )
            .satisfies(a ->
                assertThat(a.getOporCardName())
                    .as("check oporCardName")
                    .isEqualTo(expected.getOporCardName())
            )
            .satisfies(a ->
                assertThat(a.getOporComments())
                    .as("check oporComments")
                    .isEqualTo(expected.getOporComments())
            )
            .satisfies(a ->
                assertThat(a.getOporCreateDate())
                    .as("check oporCreateDate")
                    .isEqualTo(expected.getOporCreateDate())
            )
            .satisfies(a ->
                assertThat(a.getOporDepartment())
                    .as("check oporDepartment")
                    .isEqualTo(expected.getOporDepartment())
            )
            .satisfies(a ->
                assertThat(a.getOporDocDate())
                    .as("check oporDocDate")
                    .isEqualTo(expected.getOporDocDate())
            )
            .satisfies(a ->
                assertThat(a.getOporDocDueDate())
                    .as("check oporDocDueDate")
                    .isEqualTo(expected.getOporDocDueDate())
            )
            .satisfies(a ->
                assertThat(a.getOporDocEntry())
                    .as("check oporDocEntry")
                    .isEqualTo(expected.getOporDocEntry())
            )
            .satisfies(a ->
                assertThat(a.getOporDocNum())
                    .as("check oporDocNum")
                    .isEqualTo(expected.getOporDocNum())
            )
            .satisfies(a ->
                assertThat(a.getOporDocStatus())
                    .as("check oporDocStatus")
                    .isEqualTo(expected.getOporDocStatus())
            )
            .satisfies(a ->
                assertThat(a.getOporInvntSttus())
                    .as("check oporInvntSttus")
                    .isEqualTo(expected.getOporInvntSttus())
            )
            .satisfies(a ->
                assertThat(a.getOporJrnlMemo())
                    .as("check oporJrnlMemo")
                    .isEqualTo(expected.getOporJrnlMemo())
            )
            .satisfies(a ->
                assertThat(a.getOporUCoAdd())
                    .as("check oporUCoAdd")
                    .isEqualTo(expected.getOporUCoAdd())
            )
            .satisfies(a ->
                assertThat(a.getOporUCodeInv())
                    .as("check oporUCodeInv")
                    .isEqualTo(expected.getOporUCodeInv())
            )
            .satisfies(a ->
                assertThat(a.getOporUCodeSerial())
                    .as("check oporUCodeSerial")
                    .isEqualTo(expected.getOporUCodeSerial())
            )
            .satisfies(a ->
                assertThat(a.getOporUContractDate())
                    .as("check oporUContractDate")
                    .isEqualTo(expected.getOporUContractDate())
            )
            .satisfies(a ->
                assertThat(a.getOporUDeclarePd())
                    .as("check oporUDeclarePd")
                    .isEqualTo(expected.getOporUDeclarePd())
            )
            .satisfies(a ->
                assertThat(a.getOporUDocNum())
                    .as("check oporUDocNum")
                    .isEqualTo(expected.getOporUDocNum())
            )
            .satisfies(a ->
                assertThat(a.getOporUInvCode())
                    .as("check oporUInvCode")
                    .isEqualTo(expected.getOporUInvCode())
            )
            .satisfies(a ->
                assertThat(a.getOporUInvCode2())
                    .as("check oporUInvCode2")
                    .isEqualTo(expected.getOporUInvCode2())
            )
            .satisfies(a ->
                assertThat(a.getOporUInvSerial())
                    .as("check oporUInvSerial")
                    .isEqualTo(expected.getOporUInvSerial())
            )
            .satisfies(a ->
                assertThat(a.getOporUPurNVGiao())
                    .as("check oporUPurNVGiao")
                    .isEqualTo(expected.getOporUPurNVGiao())
            )
            .satisfies(a ->
                assertThat(a.getOporUpdateDate())
                    .as("check oporUpdateDate")
                    .isEqualTo(expected.getOporUpdateDate())
            )
            .satisfies(a ->
                assertThat(a.getOporUserSign())
                    .as("check oporUserSign")
                    .isEqualTo(expected.getOporUserSign())
            )
            .satisfies(a ->
                assertThat(a.getOporTaxDate())
                    .as("check oporTaxDate")
                    .isEqualTo(expected.getOporTaxDate())
            )
            .satisfies(a ->
                assertThat(a.getOporCntctCode())
                    .as("check oporCntctCode")
                    .isEqualTo(expected.getOporCntctCode())
            )
            .satisfies(a ->
                assertThat(a.getOporNumAtCard())
                    .as("check oporNumAtCard")
                    .isEqualTo(expected.getOporNumAtCard())
            )
            .satisfies(a ->
                assertThat(a.getOporSlpCode())
                    .as("check oporSlpCode")
                    .isEqualTo(expected.getOporSlpCode())
            )
            .satisfies(a ->
                assertThat(a.getOporOwnerCode())
                    .as("check oporOwnerCode")
                    .isEqualTo(expected.getOporOwnerCode())
            )
            .satisfies(a ->
                assertThat(a.getOporVatSum())
                    .as("check oporVatSum")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOporVatSum())
            )
            .satisfies(a ->
                assertThat(a.getOporDocTotal())
                    .as("check oporDocTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOporDocTotal())
            )
            .satisfies(a ->
                assertThat(a.getOporVatSumSy())
                    .as("check oporVatSumSy")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOporVatSumSy())
            )
            .satisfies(a ->
                assertThat(a.getOporUHt())
                    .as("check oporUHt")
                    .isEqualTo(expected.getOporUHt())
            )
            .satisfies(a ->
                assertThat(a.getOporUPayment())
                    .as("check oporUPayment")
                    .isEqualTo(expected.getOporUPayment())
            )
            .satisfies(a ->
                assertThat(a.getPor1BaseDocNum())
                    .as("check por1BaseDocNum")
                    .isEqualTo(expected.getPor1BaseDocNum())
            )
            .satisfies(a ->
                assertThat(a.getPor1BaseEntry())
                    .as("check por1BaseEntry")
                    .isEqualTo(expected.getPor1BaseEntry())
            )
            .satisfies(a ->
                assertThat(a.getPor1BaseLine())
                    .as("check por1BaseLine")
                    .isEqualTo(expected.getPor1BaseLine())
            )
            .satisfies(a ->
                assertThat(a.getPor1BaseRef())
                    .as("check por1BaseRef")
                    .isEqualTo(expected.getPor1BaseRef())
            )
            .satisfies(a ->
                assertThat(a.getPor1Currency())
                    .as("check por1Currency")
                    .isEqualTo(expected.getPor1Currency())
            )
            .satisfies(a ->
                assertThat(a.getPor1DiscPrcnt())
                    .as("check por1DiscPrcnt")
                    .isEqualTo(expected.getPor1DiscPrcnt())
            )
            .satisfies(a ->
                assertThat(a.getPoDocEntry())
                    .as("check poDocEntry")
                    .isEqualTo(expected.getPoDocEntry())
            )
            .satisfies(a ->
                assertThat(a.getPor1Dscription())
                    .as("check por1Dscription")
                    .isEqualTo(expected.getPor1Dscription())
            )
            .satisfies(a ->
                assertThat(a.getPor1ItemCode())
                    .as("check por1ItemCode")
                    .isEqualTo(expected.getPor1ItemCode())
            )
            .satisfies(a ->
                assertThat(a.getPor1LineNum())
                    .as("check por1LineNum")
                    .isEqualTo(expected.getPor1LineNum())
            )
            .satisfies(a ->
                assertThat(a.getPor1LineStatus())
                    .as("check por1LineStatus")
                    .isEqualTo(expected.getPor1LineStatus())
            )
            .satisfies(a ->
                assertThat(a.getPor1LineVendor())
                    .as("check por1LineVendor")
                    .isEqualTo(expected.getPor1LineVendor())
            )
            .satisfies(a ->
                assertThat(a.getPor1OpenSumSys())
                    .as("check por1OpenSumSys")
                    .isEqualTo(expected.getPor1OpenSumSys())
            )
            .satisfies(a ->
                assertThat(a.getPor1Price())
                    .as("check por1Price")
                    .isEqualTo(expected.getPor1Price())
            )
            .satisfies(a ->
                assertThat(a.getPor1Quantity())
                    .as("check por1Quantity")
                    .isEqualTo(expected.getPor1Quantity())
            )
            .satisfies(a ->
                assertThat(a.getPor1ShipDate())
                    .as("check por1ShipDate")
                    .isEqualTo(expected.getPor1ShipDate())
            )
            .satisfies(a ->
                assertThat(a.getPor1TotalFrgn())
                    .as("check por1TotalFrgn")
                    .isEqualTo(expected.getPor1TotalFrgn())
            )
            .satisfies(a ->
                assertThat(a.getPor1TotalSumsy())
                    .as("check por1TotalSumsy")
                    .isEqualTo(expected.getPor1TotalSumsy())
            )
            .satisfies(a ->
                assertThat(a.getPor1TrgetEntry())
                    .as("check por1TrgetEntry")
                    .isEqualTo(expected.getPor1TrgetEntry())
            )
            .satisfies(a ->
                assertThat(a.getPor1UMcode())
                    .as("check por1UMcode")
                    .isEqualTo(expected.getPor1UMcode())
            )
            .satisfies(a ->
                assertThat(a.getPor1USo())
                    .as("check por1USo")
                    .isEqualTo(expected.getPor1USo())
            )
            .satisfies(a ->
                assertThat(a.getPor1UTenkythuat())
                    .as("check por1UTenkythuat")
                    .isEqualTo(expected.getPor1UTenkythuat())
            )
            .satisfies(a ->
                assertThat(a.getPor1UnitMsr())
                    .as("check por1UnitMsr")
                    .isEqualTo(expected.getPor1UnitMsr())
            )
            .satisfies(a ->
                assertThat(a.getPor1UOMCode())
                    .as("check por1UOMCode")
                    .isEqualTo(expected.getPor1UOMCode())
            )
            .satisfies(a ->
                assertThat(a.getPor1VatGroup())
                    .as("check por1VatGroup")
                    .isEqualTo(expected.getPor1VatGroup())
            )
            .satisfies(a ->
                assertThat(a.getPor1LineTotal())
                    .as("check por1LineTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPor1LineTotal())
            )
            .satisfies(a ->
                assertThat(a.getPor1VatPrcnt())
                    .as("check por1VatPrcnt")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPor1VatPrcnt())
            )
            .satisfies(a ->
                assertThat(a.getPor1PriceAfVat())
                    .as("check por1PriceAfVat")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPor1PriceAfVat())
            )
            .satisfies(a ->
                assertThat(a.getPor1WhsCode())
                    .as("check por1WhsCode")
                    .isEqualTo(expected.getPor1WhsCode())
            )
            .satisfies(a ->
                assertThat(a.getPrMapPo())
                    .as("check prMapPo")
                    .isEqualTo(expected.getPrMapPo())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSapPoInfoUpdatableRelationshipsEquals(
        SapPoInfo expected,
        SapPoInfo actual
    ) {
        // empty method
    }
}
