package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SerialBoxPalletMappingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSerialBoxPalletMappingAllPropertiesEquals(
        SerialBoxPalletMapping expected,
        SerialBoxPalletMapping actual
    ) {
        assertSerialBoxPalletMappingAutoGeneratedPropertiesEquals(
            expected,
            actual
        );
        assertSerialBoxPalletMappingAllUpdatablePropertiesEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSerialBoxPalletMappingAllUpdatablePropertiesEquals(
        SerialBoxPalletMapping expected,
        SerialBoxPalletMapping actual
    ) {
        assertSerialBoxPalletMappingUpdatableFieldsEquals(expected, actual);
        assertSerialBoxPalletMappingUpdatableRelationshipsEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSerialBoxPalletMappingAutoGeneratedPropertiesEquals(
        SerialBoxPalletMapping expected,
        SerialBoxPalletMapping actual
    ) {
        assertThat(actual)
            .as("Verify SerialBoxPalletMapping auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSerialBoxPalletMappingUpdatableFieldsEquals(
        SerialBoxPalletMapping expected,
        SerialBoxPalletMapping actual
    ) {
        assertThat(actual)
            .as("Verify SerialBoxPalletMapping relevant properties")
            .satisfies(a ->
                assertThat(a.getSerialBox())
                    .as("check serialBox")
                    .isEqualTo(expected.getSerialBox())
            )
            .satisfies(a ->
                assertThat(a.getSerialPallet())
                    .as("check serialPallet")
                    .isEqualTo(expected.getSerialPallet())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .isEqualTo(expected.getUpdatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedBy())
                    .as("check updatedBy")
                    .isEqualTo(expected.getUpdatedBy())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSerialBoxPalletMappingUpdatableRelationshipsEquals(
        SerialBoxPalletMapping expected,
        SerialBoxPalletMapping actual
    ) {
        assertThat(actual)
            .as("Verify SerialBoxPalletMapping relationships")
            .satisfies(a ->
                assertThat(a.getMaLenhSanXuat())
                    .as("check maLenhSanXuat")
                    .isEqualTo(expected.getMaLenhSanXuat())
            );
    }
}
