package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TemIdentificationScenarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemIdentificationScenarioAllPropertiesEquals(
        TemIdentificationScenario expected,
        TemIdentificationScenario actual
    ) {
        assertTemIdentificationScenarioAutoGeneratedPropertiesEquals(
            expected,
            actual
        );
        assertTemIdentificationScenarioAllUpdatablePropertiesEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemIdentificationScenarioAllUpdatablePropertiesEquals(
        TemIdentificationScenario expected,
        TemIdentificationScenario actual
    ) {
        assertTemIdentificationScenarioUpdatableFieldsEquals(expected, actual);
        assertTemIdentificationScenarioUpdatableRelationshipsEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemIdentificationScenarioAutoGeneratedPropertiesEquals(
        TemIdentificationScenario expected,
        TemIdentificationScenario actual
    ) {
        assertThat(actual)
            .as("Verify TemIdentificationScenario auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemIdentificationScenarioUpdatableFieldsEquals(
        TemIdentificationScenario expected,
        TemIdentificationScenario actual
    ) {
        assertThat(actual)
            .as("Verify TemIdentificationScenario relevant properties")
            .satisfies(a ->
                assertThat(a.getVendorCode())
                    .as("check vendorCode")
                    .isEqualTo(expected.getVendorCode())
            )
            .satisfies(a ->
                assertThat(a.getVendorName())
                    .as("check vendorName")
                    .isEqualTo(expected.getVendorName())
            )
            .satisfies(a ->
                assertThat(a.getMappingConfig())
                    .as("check mappingConfig")
                    .isEqualTo(expected.getMappingConfig())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedBy())
                    .as("check updatedBy")
                    .isEqualTo(expected.getUpdatedBy())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemIdentificationScenarioUpdatableRelationshipsEquals(
        TemIdentificationScenario expected,
        TemIdentificationScenario actual
    ) {
        // empty method
    }
}
