package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class VendorTemDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorTemDetailAllPropertiesEquals(
        VendorTemDetail expected,
        VendorTemDetail actual
    ) {
        assertVendorTemDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertVendorTemDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorTemDetailAllUpdatablePropertiesEquals(
        VendorTemDetail expected,
        VendorTemDetail actual
    ) {
        assertVendorTemDetailUpdatableFieldsEquals(expected, actual);
        assertVendorTemDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorTemDetailAutoGeneratedPropertiesEquals(
        VendorTemDetail expected,
        VendorTemDetail actual
    ) {
        assertThat(actual)
            .as("Verify VendorTemDetail auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorTemDetailUpdatableFieldsEquals(
        VendorTemDetail expected,
        VendorTemDetail actual
    ) {
        assertThat(actual)
            .as("Verify VendorTemDetail relevant properties")
            .satisfies(a ->
                assertThat(a.getReelId())
                    .as("check reelId")
                    .isEqualTo(expected.getReelId())
            )
            .satisfies(a ->
                assertThat(a.getPartNumber())
                    .as("check partNumber")
                    .isEqualTo(expected.getPartNumber())
            )
            .satisfies(a ->
                assertThat(a.getVendor())
                    .as("check vendor")
                    .isEqualTo(expected.getVendor())
            )
            .satisfies(a ->
                assertThat(a.getLot())
                    .as("check lot")
                    .isEqualTo(expected.getLot())
            )
            .satisfies(a ->
                assertThat(a.getUserData1())
                    .as("check userData1")
                    .isEqualTo(expected.getUserData1())
            )
            .satisfies(a ->
                assertThat(a.getUserData2())
                    .as("check userData2")
                    .isEqualTo(expected.getUserData2())
            )
            .satisfies(a ->
                assertThat(a.getUserData3())
                    .as("check userData3")
                    .isEqualTo(expected.getUserData3())
            )
            .satisfies(a ->
                assertThat(a.getUserData4())
                    .as("check userData4")
                    .isEqualTo(expected.getUserData4())
            )
            .satisfies(a ->
                assertThat(a.getUserData5())
                    .as("check userData5")
                    .isEqualTo(expected.getUserData5())
            )
            .satisfies(a ->
                assertThat(a.getInitialQuantity())
                    .as("check initialQuantity")
                    .isEqualTo(expected.getInitialQuantity())
            )
            .satisfies(a ->
                assertThat(a.getMsdLevel())
                    .as("check msdLevel")
                    .isEqualTo(expected.getMsdLevel())
            )
            .satisfies(a ->
                assertThat(a.getMsdInitialFloorTime())
                    .as("check msdInitialFloorTime")
                    .isEqualTo(expected.getMsdInitialFloorTime())
            )
            .satisfies(a ->
                assertThat(a.getMsdBagSealDate())
                    .as("check msdBagSealDate")
                    .isEqualTo(expected.getMsdBagSealDate())
            )
            .satisfies(a ->
                assertThat(a.getMarketUsage())
                    .as("check marketUsage")
                    .isEqualTo(expected.getMarketUsage())
            )
            .satisfies(a ->
                assertThat(a.getQuantityOverride())
                    .as("check quantityOverride")
                    .isEqualTo(expected.getQuantityOverride())
            )
            .satisfies(a ->
                assertThat(a.getShelfTime())
                    .as("check shelfTime")
                    .isEqualTo(expected.getShelfTime())
            )
            .satisfies(a ->
                assertThat(a.getSpMaterialName())
                    .as("check spMaterialName")
                    .isEqualTo(expected.getSpMaterialName())
            )
            .satisfies(a ->
                assertThat(a.getWarningLimit())
                    .as("check warningLimit")
                    .isEqualTo(expected.getWarningLimit())
            )
            .satisfies(a ->
                assertThat(a.getMaximumLimit())
                    .as("check maximumLimit")
                    .isEqualTo(expected.getMaximumLimit())
            )
            .satisfies(a ->
                assertThat(a.getComments())
                    .as("check comments")
                    .isEqualTo(expected.getComments())
            )
            .satisfies(a ->
                assertThat(a.getWarmupTime())
                    .as("check warmupTime")
                    .isEqualTo(expected.getWarmupTime())
            )
            .satisfies(a ->
                assertThat(a.getStorageUnit())
                    .as("check storageUnit")
                    .isEqualTo(expected.getStorageUnit())
            )
            .satisfies(a ->
                assertThat(a.getSubStorageUnit())
                    .as("check subStorageUnit")
                    .isEqualTo(expected.getSubStorageUnit())
            )
            .satisfies(a ->
                assertThat(a.getLocationOverride())
                    .as("check locationOverride")
                    .isEqualTo(expected.getLocationOverride())
            )
            .satisfies(a ->
                assertThat(a.getExpirationDate())
                    .as("check expirationDate")
                    .isEqualTo(expected.getExpirationDate())
            )
            .satisfies(a ->
                assertThat(a.getManufacturingDate())
                    .as("check manufacturingDate")
                    .isEqualTo(expected.getManufacturingDate())
            )
            .satisfies(a ->
                assertThat(a.getPartClass())
                    .as("check partClass")
                    .isEqualTo(expected.getPartClass())
            )
            .satisfies(a ->
                assertThat(a.getSapCode())
                    .as("check sapCode")
                    .isEqualTo(expected.getSapCode())
            )
            .satisfies(a ->
                assertThat(a.getVendorQrCode())
                    .as("check vendorQrCode")
                    .isEqualTo(expected.getVendorQrCode())
            )
            .satisfies(a ->
                assertThat(a.getStatus())
                    .as("check status")
                    .isEqualTo(expected.getStatus())
            )
            .satisfies(a ->
                assertThat(a.getCreatedBy())
                    .as("check createdBy")
                    .isEqualTo(expected.getCreatedBy())
            )
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedBy())
                    .as("check updatedBy")
                    .isEqualTo(expected.getUpdatedBy())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorTemDetailUpdatableRelationshipsEquals(
        VendorTemDetail expected,
        VendorTemDetail actual
    ) {
        assertThat(actual)
            .as("Verify VendorTemDetail relationships")
            .satisfies(a ->
                assertThat(a.getPoDetail())
                    .as("check poDetail")
                    .isEqualTo(expected.getPoDetail())
            );
    }
}
