package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WarehouseStampInfoDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoDetailAllPropertiesEquals(
        WarehouseStampInfoDetail expected,
        WarehouseStampInfoDetail actual
    ) {
        assertWarehouseStampInfoDetailAutoGeneratedPropertiesEquals(
            expected,
            actual
        );
        assertWarehouseStampInfoDetailAllUpdatablePropertiesEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoDetailAllUpdatablePropertiesEquals(
        WarehouseStampInfoDetail expected,
        WarehouseStampInfoDetail actual
    ) {
        assertWarehouseStampInfoDetailUpdatableFieldsEquals(expected, actual);
        assertWarehouseStampInfoDetailUpdatableRelationshipsEquals(
            expected,
            actual
        );
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoDetailAutoGeneratedPropertiesEquals(
        WarehouseStampInfoDetail expected,
        WarehouseStampInfoDetail actual
    ) {
        assertThat(actual)
            .as("Verify WarehouseStampInfoDetail auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoDetailUpdatableFieldsEquals(
        WarehouseStampInfoDetail expected,
        WarehouseStampInfoDetail actual
    ) {
        assertThat(actual)
            .as("Verify WarehouseStampInfoDetail relevant properties")
            .satisfies(a ->
                assertThat(a.getReelId())
                    .as("check reelId")
                    .isEqualTo(expected.getReelId())
            )
            .satisfies(a ->
                assertThat(a.getPartNumber())
                    .as("check partNumber")
                    .isEqualTo(expected.getPartNumber())
            )
            .satisfies(a ->
                assertThat(a.getVendor())
                    .as("check vendor")
                    .isEqualTo(expected.getVendor())
            )
            .satisfies(a ->
                assertThat(a.getLot())
                    .as("check lot")
                    .isEqualTo(expected.getLot())
            )
            .satisfies(a ->
                assertThat(a.getUserData1())
                    .as("check userData1")
                    .isEqualTo(expected.getUserData1())
            )
            .satisfies(a ->
                assertThat(a.getUserData2())
                    .as("check userData2")
                    .isEqualTo(expected.getUserData2())
            )
            .satisfies(a ->
                assertThat(a.getUserData3())
                    .as("check userData3")
                    .isEqualTo(expected.getUserData3())
            )
            .satisfies(a ->
                assertThat(a.getUserData4())
                    .as("check userData4")
                    .isEqualTo(expected.getUserData4())
            )
            .satisfies(a ->
                assertThat(a.getUserData5())
                    .as("check userData5")
                    .isEqualTo(expected.getUserData5())
            )
            .satisfies(a ->
                assertThat(a.getInitialQuantity())
                    .as("check initialQuantity")
                    .isEqualTo(expected.getInitialQuantity())
            )
            .satisfies(a ->
                assertThat(a.getMsdLevel())
                    .as("check msdLevel")
                    .isEqualTo(expected.getMsdLevel())
            )
            .satisfies(a ->
                assertThat(a.getMsdInitialFloorTime())
                    .as("check msdInitialFloorTime")
                    .isEqualTo(expected.getMsdInitialFloorTime())
            )
            .satisfies(a ->
                assertThat(a.getMsdBagSealDate())
                    .as("check msdBagSealDate")
                    .isEqualTo(expected.getMsdBagSealDate())
            )
            .satisfies(a ->
                assertThat(a.getMarketUsage())
                    .as("check marketUsage")
                    .isEqualTo(expected.getMarketUsage())
            )
            .satisfies(a ->
                assertThat(a.getQuantityOverride())
                    .as("check quantityOverride")
                    .isEqualTo(expected.getQuantityOverride())
            )
            .satisfies(a ->
                assertThat(a.getShelfTime())
                    .as("check shelfTime")
                    .isEqualTo(expected.getShelfTime())
            )
            .satisfies(a ->
                assertThat(a.getSpMaterialName())
                    .as("check spMaterialName")
                    .isEqualTo(expected.getSpMaterialName())
            )
            .satisfies(a ->
                assertThat(a.getWarningLimit())
                    .as("check warningLimit")
                    .isEqualTo(expected.getWarningLimit())
            )
            .satisfies(a ->
                assertThat(a.getMaximumLimit())
                    .as("check maximumLimit")
                    .isEqualTo(expected.getMaximumLimit())
            )
            .satisfies(a ->
                assertThat(a.getComments())
                    .as("check comments")
                    .isEqualTo(expected.getComments())
            )
            .satisfies(a ->
                assertThat(a.getWarmupTime())
                    .as("check warmupTime")
                    .isEqualTo(expected.getWarmupTime())
            )
            .satisfies(a ->
                assertThat(a.getStorageUnit())
                    .as("check storageUnit")
                    .isEqualTo(expected.getStorageUnit())
            )
            .satisfies(a ->
                assertThat(a.getSubStorageUnit())
                    .as("check subStorageUnit")
                    .isEqualTo(expected.getSubStorageUnit())
            )
            .satisfies(a ->
                assertThat(a.getLocationOverride())
                    .as("check locationOverride")
                    .isEqualTo(expected.getLocationOverride())
            )
            .satisfies(a ->
                assertThat(a.getExpirationDate())
                    .as("check expirationDate")
                    .isEqualTo(expected.getExpirationDate())
            )
            .satisfies(a ->
                assertThat(a.getManufacturingDate())
                    .as("check manufacturingDate")
                    .isEqualTo(expected.getManufacturingDate())
            )
            .satisfies(a ->
                assertThat(a.getPartClass())
                    .as("check partClass")
                    .isEqualTo(expected.getPartClass())
            )
            .satisfies(a ->
                assertThat(a.getSapCode())
                    .as("check sapCode")
                    .isEqualTo(expected.getSapCode())
            )
            .satisfies(a ->
                assertThat(a.getLenhSanXuatId())
                    .as("check lenhSanXuatId")
                    .isEqualTo(expected.getLenhSanXuatId())
            )
            .satisfies(a ->
                assertThat(a.getTrangThai())
                    .as("check trangThai")
                    .isEqualTo(expected.getTrangThai())
            )
            .satisfies(a ->
                assertThat(a.getChecked())
                    .as("check checked")
                    .isEqualTo(expected.getChecked())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoDetailUpdatableRelationshipsEquals(
        WarehouseStampInfoDetail expected,
        WarehouseStampInfoDetail actual
    ) {
        assertThat(actual)
            .as("Verify WarehouseStampInfoDetail relationships")
            .satisfies(a ->
                assertThat(a.getMaLenhSanXuat())
                    .as("check maLenhSanXuat")
                    .isEqualTo(expected.getMaLenhSanXuat())
            );
    }
}
