package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WarehouseStampInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoAllPropertiesEquals(
        WarehouseStampInfo expected,
        WarehouseStampInfo actual
    ) {
        assertWarehouseStampInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertWarehouseStampInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoAllUpdatablePropertiesEquals(
        WarehouseStampInfo expected,
        WarehouseStampInfo actual
    ) {
        assertWarehouseStampInfoUpdatableFieldsEquals(expected, actual);
        assertWarehouseStampInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoAutoGeneratedPropertiesEquals(
        WarehouseStampInfo expected,
        WarehouseStampInfo actual
    ) {
        assertThat(actual)
            .as("Verify WarehouseStampInfo auto generated properties")
            .satisfies(a ->
                assertThat(a.getId()).as("check id").isEqualTo(expected.getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoUpdatableFieldsEquals(
        WarehouseStampInfo expected,
        WarehouseStampInfo actual
    ) {
        assertThat(actual)
            .as("Verify WarehouseStampInfo relevant properties")
            .satisfies(a ->
                assertThat(a.getMaLenhSanXuat())
                    .as("check maLenhSanXuat")
                    .isEqualTo(expected.getMaLenhSanXuat())
            )
            .satisfies(a ->
                assertThat(a.getSapCode())
                    .as("check sapCode")
                    .isEqualTo(expected.getSapCode())
            )
            .satisfies(a ->
                assertThat(a.getSapName())
                    .as("check sapName")
                    .isEqualTo(expected.getSapName())
            )
            .satisfies(a ->
                assertThat(a.getWorkOrderCode())
                    .as("check workOrderCode")
                    .isEqualTo(expected.getWorkOrderCode())
            )
            .satisfies(a ->
                assertThat(a.getVersion())
                    .as("check version")
                    .isEqualTo(expected.getVersion())
            )
            .satisfies(a ->
                assertThat(a.getStorageCode())
                    .as("check storageCode")
                    .isEqualTo(expected.getStorageCode())
            )
            .satisfies(a ->
                assertThat(a.getTotalQuantity())
                    .as("check totalQuantity")
                    .isEqualTo(expected.getTotalQuantity())
            )
            .satisfies(a ->
                assertThat(a.getCreateBy())
                    .as("check createBy")
                    .isEqualTo(expected.getCreateBy())
            )
            .satisfies(a ->
                assertThat(a.getEntryTime())
                    .as("check entryTime")
                    .isEqualTo(expected.getEntryTime())
            )
            .satisfies(a ->
                assertThat(a.getTrangThai())
                    .as("check trangThai")
                    .isEqualTo(expected.getTrangThai())
            )
            .satisfies(a ->
                assertThat(a.getComment())
                    .as("check comment")
                    .isEqualTo(expected.getComment())
            )
            .satisfies(a ->
                assertThat(a.getTimeUpdate())
                    .as("check timeUpdate")
                    .isEqualTo(expected.getTimeUpdate())
            )
            .satisfies(a ->
                assertThat(a.getGroupName())
                    .as("check groupName")
                    .isEqualTo(expected.getGroupName())
            )
            .satisfies(a ->
                assertThat(a.getComment2())
                    .as("check comment2")
                    .isEqualTo(expected.getComment2())
            )
            .satisfies(a ->
                assertThat(a.getApproverBy())
                    .as("check approverBy")
                    .isEqualTo(expected.getApproverBy())
            )
            .satisfies(a ->
                assertThat(a.getBranch())
                    .as("check branch")
                    .isEqualTo(expected.getBranch())
            )
            .satisfies(a ->
                assertThat(a.getProductType())
                    .as("check productType")
                    .isEqualTo(expected.getProductType())
            )
            .satisfies(a ->
                assertThat(a.getDeletedAt())
                    .as("check deletedAt")
                    .isEqualTo(expected.getDeletedAt())
            )
            .satisfies(a ->
                assertThat(a.getDeletedBy())
                    .as("check deletedBy")
                    .isEqualTo(expected.getDeletedBy())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseStampInfoUpdatableRelationshipsEquals(
        WarehouseStampInfo expected,
        WarehouseStampInfo actual
    ) {
        // empty method
    }
}
